spring.application.name=test
#本地端測試
server.port=8080
#Azure端測試
spring.datasource.url=jdbc:mysql://twenty48.mysql.database.azure.com:3306/twenty48?useSSL=true&requireSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=b11013039
spring.datasource.password=@Ss1234567890

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
